server {
    listen 80;

    # SmolLM2 API
    location /api/ {
        proxy_pass http://smollm2-seed:3000/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    # NextChat
    location / {
        proxy_pass http://nextchat:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
